//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.6.0.
//
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package co.siempo.phone.app;

import android.content.Context;
import android.content.SharedPreferences;

import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.FloatPrefEditorField;
import org.androidannotations.api.sharedpreferences.FloatPrefField;
import org.androidannotations.api.sharedpreferences.IntPrefEditorField;
import org.androidannotations.api.sharedpreferences.IntPrefField;
import org.androidannotations.api.sharedpreferences.LongPrefEditorField;
import org.androidannotations.api.sharedpreferences.LongPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

/**
 * This is an autogenerated class, generated by AndroidAnnotations.
 */
public final class DroidPrefs_ extends SharedPreferencesHelper {
    public DroidPrefs_(Context context) {
        super(context.getSharedPreferences("DroidPrefs", 0));
    }

    public DroidPrefs_.DroidPrefsEditor_ edit() {
        return new DroidPrefs_.DroidPrefsEditor_(getSharedPreferences());
    }

    /**
     * <p><b>Defaults to</b>: -16777216</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField selectedThemeColor() {
        return intField("selectedThemeColor", -16777216);
    }

    /**
     * <p><b>Defaults to</b>: 0</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField selectedThemeId() {
        return intField("selectedThemeId", 0);
    }

    /**
     * <p><b>Defaults to</b>: 0</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField notificationScheduleIndex() {
        return intField("notificationScheduleIndex", 0);
    }

    /**
     * <p><b>Defaults to</b>: 0</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField notificationSchedulerValue() {
        return intField("notificationSchedulerValue", 0);
    }

    /**
     * <p><b>Defaults to</b>: 0</p>
     *
     * @return a {@link LongPrefField} instance to retrieve or write the pref value
     */
    public LongPrefField notificationScheulerNextMillis() {
        return longField("notificationScheulerNextMillis", 0L);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField notificationSchedulerSupressCalls() {
        return booleanField("notificationSchedulerSupressCalls", true);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField notificationSchedulerSupressSMS() {
        return booleanField("notificationSchedulerSupressSMS", true);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isFlowRunning() {
        return booleanField("isFlowRunning", false);
    }

    /**
     * <p><b>Defaults to</b>: 0.0</p>
     *
     * @return a {@link FloatPrefField} instance to retrieve or write the pref value
     */
    public FloatPrefField flowMaxTimeLimitMillis() {
        return floatField("flowMaxTimeLimitMillis", 0.0F);
    }

    /**
     * <p><b>Defaults to</b>: 0.0</p>
     *
     * @return a {@link FloatPrefField} instance to retrieve or write the pref value
     */
    public FloatPrefField flowSegmentDurationMillis() {
        return floatField("flowSegmentDurationMillis", 0.0F);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     * true - Notification Scheduler could not display scheduled notification due to other prioritized action (i.e. Flow)
     * false - otherwise
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isNotificationSupressed() {
        return booleanField("isNotificationSupressed", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isNotificationSchedulerEnabled() {
        return booleanField("isNotificationSchedulerEnabled", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isSiempoNotificationServiceRunning() {
        return booleanField("isSiempoNotificationServiceRunning", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField hasShownIntroScreen() {
        return booleanField("hasShownIntroScreen", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     * This preference is used for store
     * user preference for Grid/List in Menu Listing View.
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isMenuGrid() {
        return booleanField("isMenuGrid", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField sortedMenu() {
        return stringField("sortedMenu", "");
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     * This preference is used for store
     * user preference for Grid/List in App Listing View.
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isGrid() {
        return booleanField("isGrid", true);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isContactUpdate() {
        return booleanField("isContactUpdate", true);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isAppUpdated() {
        return booleanField("isAppUpdated", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField callPackage() {
        return stringField("callPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isCallClicked() {
        return booleanField("isCallClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isCallClickedFirstTime() {
        return booleanField("isCallClickedFirstTime", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField messagePackage() {
        return stringField("messagePackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isMessageClicked() {
        return booleanField("isMessageClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isMessageClickedFirstTime() {
        return booleanField("isMessageClickedFirstTime", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField calenderPackage() {
        return stringField("calenderPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isCalenderClicked() {
        return booleanField("isCalenderClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField contactPackage() {
        return stringField("contactPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isContactClicked() {
        return booleanField("isContactClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField mapPackage() {
        return stringField("mapPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isMapClicked() {
        return booleanField("isMapClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField photosPackage() {
        return stringField("photosPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isPhotosClicked() {
        return booleanField("isPhotosClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField cameraPackage() {
        return stringField("cameraPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isCameraClicked() {
        return booleanField("isCameraClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField browserPackage() {
        return stringField("browserPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isBrowserClicked() {
        return booleanField("isBrowserClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField clockPackage() {
        return stringField("clockPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isClockClicked() {
        return booleanField("isClockClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField emailPackage() {
        return stringField("emailPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField notesPackage() {
        return stringField("notesPackage", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isEmailClicked() {
        return booleanField("isEmailClicked", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isEmailClickedFirstTime() {
        return booleanField("isEmailClickedFirstTime", false);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isFacebookAllowed() {
        return booleanField("isFacebookAllowed", true);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isFacebooKMessangerAllowed() {
        return booleanField("isFacebooKMessangerAllowed", true);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isFacebooKMessangerLiteAllowed() {
        return booleanField("isFacebooKMessangerLiteAllowed", true);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isWhatsAppAllowed() {
        return booleanField("isWhatsAppAllowed", true);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isHangOutAllowed() {
        return booleanField("isHangOutAllowed", true);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isAlphaSettingEnable() {
        return booleanField("isAlphaSettingEnable", false);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isFireBaseAnalyticsEnable() {
        return booleanField("isFireBaseAnalyticsEnable", true);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isTempoNotificationControlsDisabled() {
        return booleanField("isTempoNotificationControlsDisabled", false);
    }

    /**
     * <p><b>Defaults to</b>: 0</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField tempoType() {
        return intField("tempoType", 0);
    }

    /**
     * <p><b>Defaults to</b>: 15</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField batchTime() {
        return intField("batchTime", 15);
    }

    /**
     * <p><b>Defaults to</b>: "12:01"</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField onlyAt() {
        return stringField("onlyAt", "12:01");
    }

    /**
     * <p><b>Defaults to</b>: 0</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField tempoSoundProfile() {
        return intField("tempoSoundProfile", 0);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField userEmailId() {
        return stringField("userEmailId", "");
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isIntentionEnable() {
        return booleanField("isIntentionEnable", false);
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField defaultIntention() {
        return stringField("defaultIntention", "");
    }

    public final static class DroidPrefsEditor_
            extends EditorHelper<DroidPrefs_.DroidPrefsEditor_> {

        DroidPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public IntPrefEditorField<DroidPrefs_.DroidPrefsEditor_> selectedThemeColor() {
            return intField("selectedThemeColor");
        }

        public IntPrefEditorField<DroidPrefs_.DroidPrefsEditor_> selectedThemeId() {
            return intField("selectedThemeId");
        }

        public IntPrefEditorField<DroidPrefs_.DroidPrefsEditor_> notificationScheduleIndex() {
            return intField("notificationScheduleIndex");
        }

        public IntPrefEditorField<DroidPrefs_.DroidPrefsEditor_> notificationSchedulerValue() {
            return intField("notificationSchedulerValue");
        }

        public LongPrefEditorField<DroidPrefs_.DroidPrefsEditor_> notificationScheulerNextMillis() {
            return longField("notificationScheulerNextMillis");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> notificationSchedulerSupressCalls() {
            return booleanField("notificationSchedulerSupressCalls");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> notificationSchedulerSupressSMS() {
            return booleanField("notificationSchedulerSupressSMS");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isFlowRunning() {
            return booleanField("isFlowRunning");
        }

        public FloatPrefEditorField<DroidPrefs_.DroidPrefsEditor_> flowMaxTimeLimitMillis() {
            return floatField("flowMaxTimeLimitMillis");
        }

        public FloatPrefEditorField<DroidPrefs_.DroidPrefsEditor_> flowSegmentDurationMillis() {
            return floatField("flowSegmentDurationMillis");
        }

        /**
         * true - Notification Scheduler could not display scheduled notification due to other prioritized action (i.e. Flow)
         * false - otherwise
         *
         * @return
         */
        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isNotificationSupressed() {
            return booleanField("isNotificationSupressed");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isNotificationSchedulerEnabled() {
            return booleanField("isNotificationSchedulerEnabled");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isSiempoNotificationServiceRunning() {
            return booleanField("isSiempoNotificationServiceRunning");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> hasShownIntroScreen() {
            return booleanField("hasShownIntroScreen");
        }

        /**
         * This preference is used for store
         * user preference for Grid/List in Menu Listing View.
         *
         * @return
         */
        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isMenuGrid() {
            return booleanField("isMenuGrid");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> sortedMenu() {
            return stringField("sortedMenu");
        }

        /**
         * This preference is used for store
         * user preference for Grid/List in App Listing View.
         *
         * @return
         */
        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isGrid() {
            return booleanField("isGrid");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isContactUpdate() {
            return booleanField("isContactUpdate");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isAppUpdated() {
            return booleanField("isAppUpdated");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> callPackage() {
            return stringField("callPackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isCallClicked() {
            return booleanField("isCallClicked");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isCallClickedFirstTime() {
            return booleanField("isCallClickedFirstTime");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> messagePackage() {
            return stringField("messagePackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isMessageClicked() {
            return booleanField("isMessageClicked");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isMessageClickedFirstTime() {
            return booleanField("isMessageClickedFirstTime");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> calenderPackage() {
            return stringField("calenderPackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isCalenderClicked() {
            return booleanField("isCalenderClicked");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> contactPackage() {
            return stringField("contactPackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isContactClicked() {
            return booleanField("isContactClicked");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> mapPackage() {
            return stringField("mapPackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isMapClicked() {
            return booleanField("isMapClicked");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> photosPackage() {
            return stringField("photosPackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isPhotosClicked() {
            return booleanField("isPhotosClicked");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> cameraPackage() {
            return stringField("cameraPackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isCameraClicked() {
            return booleanField("isCameraClicked");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> browserPackage() {
            return stringField("browserPackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isBrowserClicked() {
            return booleanField("isBrowserClicked");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> clockPackage() {
            return stringField("clockPackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isClockClicked() {
            return booleanField("isClockClicked");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> emailPackage() {
            return stringField("emailPackage");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> notesPackage() {
            return stringField("notesPackage");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isEmailClicked() {
            return booleanField("isEmailClicked");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isEmailClickedFirstTime() {
            return booleanField("isEmailClickedFirstTime");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isFacebookAllowed() {
            return booleanField("isFacebookAllowed");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isFacebooKMessangerAllowed() {
            return booleanField("isFacebooKMessangerAllowed");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isFacebooKMessangerLiteAllowed() {
            return booleanField("isFacebooKMessangerLiteAllowed");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isWhatsAppAllowed() {
            return booleanField("isWhatsAppAllowed");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isHangOutAllowed() {
            return booleanField("isHangOutAllowed");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isAlphaSettingEnable() {
            return booleanField("isAlphaSettingEnable");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isFireBaseAnalyticsEnable() {
            return booleanField("isFireBaseAnalyticsEnable");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isTempoNotificationControlsDisabled() {
            return booleanField("isTempoNotificationControlsDisabled");
        }

        public IntPrefEditorField<DroidPrefs_.DroidPrefsEditor_> tempoType() {
            return intField("tempoType");
        }

        public IntPrefEditorField<DroidPrefs_.DroidPrefsEditor_> batchTime() {
            return intField("batchTime");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> onlyAt() {
            return stringField("onlyAt");
        }

        public IntPrefEditorField<DroidPrefs_.DroidPrefsEditor_> tempoSoundProfile() {
            return intField("tempoSoundProfile");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> userEmailId() {
            return stringField("userEmailId");
        }

        public BooleanPrefEditorField<DroidPrefs_.DroidPrefsEditor_> isIntentionEnable() {
            return booleanField("isIntentionEnable");
        }

        public StringPrefEditorField<DroidPrefs_.DroidPrefsEditor_> defaultIntention() {
            return stringField("defaultIntention");
        }
    }
}