//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.6.0.
//
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package co.siempo.phone.app;

import android.content.Context;
import android.content.SharedPreferences;

import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.IntPrefEditorField;
import org.androidannotations.api.sharedpreferences.IntPrefField;
import org.androidannotations.api.sharedpreferences.LongPrefEditorField;
import org.androidannotations.api.sharedpreferences.LongPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

/**
 * This is an autogenerated class generated by AndroidAnnotations
 */
public final class Launcher3Prefs_ extends SharedPreferencesHelper {
    public Launcher3Prefs_(Context context) {
        super(context.getSharedPreferences("Launcher3Prefs", 0));
    }

    public Launcher3Prefs_.Launcher3PrefsEditor_ edit() {
        return new Launcher3Prefs_.Launcher3PrefsEditor_(getSharedPreferences());
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isPauseActive() {
        return booleanField("isPauseActive", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isPauseAllowFavoriteChecked() {
        return booleanField("isPauseAllowFavoriteChecked", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isPauseAllowCallsChecked() {
        return booleanField("isPauseAllowCallsChecked", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isNotificationBlockerRunning() {
        return booleanField("isNotificationBlockerRunning", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isTempoActive() {
        return booleanField("isTempoActive", false);
    }

    /**
     * <p><b>Defaults to</b>: 0</p>
     *
     * @return a {@link LongPrefField} instance to retrieve or write the pref value
     */
    public LongPrefField tempoNextNotificationMillis() {
        return longField("tempoNextNotificationMillis", 0L);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField tempoAllowFavorites() {
        return booleanField("tempoAllowFavorites", false);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField tempoAllowCalls() {
        return booleanField("tempoAllowCalls", false);
    }

    /**
     * <p><b>Defaults to</b>: 15</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField tempoIntervalMinutes() {
        return intField("tempoIntervalMinutes", 15);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isAwayChecked() {
        return booleanField("isAwayChecked", false);
    }

    /**
     * <p><b>Defaults to</b>: "10:20:1"</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField time() {
        return stringField("time", "10:20:1");
    }

    /**
     * <p><b>Defaults to</b>: ""</p>
     *
     * @return a {@link StringPrefField} instance to retrieve or write the pref value
     */
    public StringPrefField awayMessage() {
        return stringField("awayMessage", "");
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField updatePrompt() {
        return booleanField("updatePrompt", true);
    }

    /**
     * <p><b>Defaults to</b>: true</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isAppInstalledFirstTime() {
        return booleanField("isAppInstalledFirstTime", true);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isKeyBoardDisplay() {
        return booleanField("isKeyBoardDisplay", false);
    }

    /**
     * <p><b>Defaults to</b>: 0</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField getCurrentProfile() {
        return intField("getCurrentProfile", 0);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isAppDefaultOrFront() {
        return booleanField("isAppDefaultOrFront", false);
    }

    /**
     * <p><b>Defaults to</b>: 0</p>
     *
     * @return a {@link IntPrefField} instance to retrieve or write the pref value
     */
    public IntPrefField getCurrentVersion() {
        return intField("getCurrentVersion", 0);
    }

    /**
     * <p><b>Defaults to</b>: false</p>
     *
     * @return a {@link BooleanPrefField} instance to retrieve or write the pref value
     */
    public BooleanPrefField isPermissionGivenAndContinued() {
        return booleanField("isPermissionGivenAndContinued", false);
    }

    public final static class Launcher3PrefsEditor_
            extends EditorHelper<Launcher3Prefs_.Launcher3PrefsEditor_> {

        Launcher3PrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isPauseActive() {
            return booleanField("isPauseActive");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isPauseAllowFavoriteChecked() {
            return booleanField("isPauseAllowFavoriteChecked");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isPauseAllowCallsChecked() {
            return booleanField("isPauseAllowCallsChecked");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isNotificationBlockerRunning() {
            return booleanField("isNotificationBlockerRunning");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isTempoActive() {
            return booleanField("isTempoActive");
        }

        public LongPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> tempoNextNotificationMillis() {
            return longField("tempoNextNotificationMillis");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> tempoAllowFavorites() {
            return booleanField("tempoAllowFavorites");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> tempoAllowCalls() {
            return booleanField("tempoAllowCalls");
        }

        public IntPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> tempoIntervalMinutes() {
            return intField("tempoIntervalMinutes");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isAwayChecked() {
            return booleanField("isAwayChecked");
        }

        public StringPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> time() {
            return stringField("time");
        }

        public StringPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> awayMessage() {
            return stringField("awayMessage");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> updatePrompt() {
            return booleanField("updatePrompt");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isAppInstalledFirstTime() {
            return booleanField("isAppInstalledFirstTime");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isKeyBoardDisplay() {
            return booleanField("isKeyBoardDisplay");
        }

        public IntPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> getCurrentProfile() {
            return intField("getCurrentProfile");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isAppDefaultOrFront() {
            return booleanField("isAppDefaultOrFront");
        }

        public IntPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> getCurrentVersion() {
            return intField("getCurrentVersion");
        }

        public BooleanPrefEditorField<Launcher3Prefs_.Launcher3PrefsEditor_> isPermissionGivenAndContinued() {
            return booleanField("isPermissionGivenAndContinued");
        }
    }
}